apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedchat
  template:
    metadata:
      labels:
        app: embedchat
    spec:
      containers:
        - name: embedchat
          image: recycle-ai:latest
          envFrom:
            - secretRef:
                name: secret-openai
            - configMapRef:
                name: configmap-sentinel
          stdin: true
          tty: true
          command: ["bash","-lc","python sentinel_agent.py"]
